package mybatis.dao;

import mybatis.model.ReservationRoom;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ReservationRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION_ROOM
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    int insert(ReservationRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION_ROOM
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    List<ReservationRoom> selectAll();
}