package mybatis.dao;

import mybatis.model.Reservation;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ReservationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    int insert(Reservation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    Reservation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    List<Reservation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RESERVATION
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    int updateByPrimaryKey(Reservation record);
}