package mybatis.model;

public class Hotel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HOTEL.ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HOTEL.NAME
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HOTEL.STREET_ADDRESS
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private String streetAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HOTEL.ID
     *
     * @return the value of PUBLIC.HOTEL.ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HOTEL.ID
     *
     * @param id the value for PUBLIC.HOTEL.ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HOTEL.NAME
     *
     * @return the value of PUBLIC.HOTEL.NAME
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HOTEL.NAME
     *
     * @param name the value for PUBLIC.HOTEL.NAME
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HOTEL.STREET_ADDRESS
     *
     * @return the value of PUBLIC.HOTEL.STREET_ADDRESS
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HOTEL.STREET_ADDRESS
     *
     * @param streetAddress the value for PUBLIC.HOTEL.STREET_ADDRESS
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }
}