package mybatis.model;

public class Reservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.CUSTOMER_NAME
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.FROM_DATE
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private String fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION.TO_DATE
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private String toDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.ID
     *
     * @return the value of PUBLIC.RESERVATION.ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.ID
     *
     * @param id the value for PUBLIC.RESERVATION.ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.CUSTOMER_NAME
     *
     * @return the value of PUBLIC.RESERVATION.CUSTOMER_NAME
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.CUSTOMER_NAME
     *
     * @param customerName the value for PUBLIC.RESERVATION.CUSTOMER_NAME
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.FROM_DATE
     *
     * @return the value of PUBLIC.RESERVATION.FROM_DATE
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public String getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.FROM_DATE
     *
     * @param fromDate the value for PUBLIC.RESERVATION.FROM_DATE
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setFromDate(String fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION.TO_DATE
     *
     * @return the value of PUBLIC.RESERVATION.TO_DATE
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public String getToDate() {
        return toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION.TO_DATE
     *
     * @param toDate the value for PUBLIC.RESERVATION.TO_DATE
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setToDate(String toDate) {
        this.toDate = toDate;
    }
}