package mybatis.model;

public class ReservationRoom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION_ROOM.RESERVATION_ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private Long reservationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.RESERVATION_ROOM.ROOM_ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private Long roomId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION_ROOM.RESERVATION_ID
     *
     * @return the value of PUBLIC.RESERVATION_ROOM.RESERVATION_ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public Long getReservationId() {
        return reservationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION_ROOM.RESERVATION_ID
     *
     * @param reservationId the value for PUBLIC.RESERVATION_ROOM.RESERVATION_ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setReservationId(Long reservationId) {
        this.reservationId = reservationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.RESERVATION_ROOM.ROOM_ID
     *
     * @return the value of PUBLIC.RESERVATION_ROOM.ROOM_ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public Long getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.RESERVATION_ROOM.ROOM_ID
     *
     * @param roomId the value for PUBLIC.RESERVATION_ROOM.ROOM_ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }
}