package mybatis.model;

public class Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.NUMBER
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.TYPE
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.HOTEL_ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    private Long hotelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.ID
     *
     * @return the value of PUBLIC.ROOM.ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.ID
     *
     * @param id the value for PUBLIC.ROOM.ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.NUMBER
     *
     * @return the value of PUBLIC.ROOM.NUMBER
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.NUMBER
     *
     * @param number the value for PUBLIC.ROOM.NUMBER
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.TYPE
     *
     * @return the value of PUBLIC.ROOM.TYPE
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.TYPE
     *
     * @param type the value for PUBLIC.ROOM.TYPE
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.HOTEL_ID
     *
     * @return the value of PUBLIC.ROOM.HOTEL_ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public Long getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.HOTEL_ID
     *
     * @param hotelId the value for PUBLIC.ROOM.HOTEL_ID
     *
     * @mbg.generated Sun Apr 07 18:46:01 EEST 2019
     */
    public void setHotelId(Long hotelId) {
        this.hotelId = hotelId;
    }
}